from fastapi import APIRouter, HTTPException, Query
from typing import Optional
from datetime import datetime, timedelta
import random

router = APIRouter(prefix="/workspaces", tags=["Forecast Workspaces"])

projects_store = [
    {
        "id": 1, "name": "Q4 Electronics Forecast", "description": "Quarterly demand forecast for Electronics division",
        "owner": "admin@example.com", "members": ["admin@example.com", "analyst@example.com"],
        "status": "active", "category": "Electronics", "region": "North",
        "dataset_count": 3, "forecast_count": 8, "report_count": 4,
        "permissions": {"view": ["all"], "edit": ["admin", "analyst"], "delete": ["admin"]},
        "tags": ["quarterly", "electronics", "high-priority"],
        "created_at": (datetime.utcnow() - timedelta(days=30)).isoformat(),
        "updated_at": (datetime.utcnow() - timedelta(hours=5)).isoformat(),
        "last_activity": "Forecast run by analyst@example.com 2h ago",
    },
    {
        "id": 2, "name": "Annual Fashion Planning", "description": "Full-year seasonal fashion demand planning",
        "owner": "manager@example.com", "members": ["manager@example.com", "admin@example.com"],
        "status": "active", "category": "Fashion", "region": "All",
        "dataset_count": 5, "forecast_count": 12, "report_count": 6,
        "permissions": {"view": ["all"], "edit": ["admin", "manager"], "delete": ["admin"]},
        "tags": ["annual", "fashion", "seasonal"],
        "created_at": (datetime.utcnow() - timedelta(days=60)).isoformat(),
        "updated_at": (datetime.utcnow() - timedelta(days=1)).isoformat(),
        "last_activity": "Report generated by manager@example.com 1d ago",
    },
    {
        "id": 3, "name": "Grocery Restock Planning", "description": "Weekly grocery restock and demand management",
        "owner": "analyst@example.com", "members": ["analyst@example.com"],
        "status": "archived", "category": "Groceries", "region": "South",
        "dataset_count": 2, "forecast_count": 5, "report_count": 2,
        "permissions": {"view": ["admin", "analyst"], "edit": ["analyst"], "delete": ["admin"]},
        "tags": ["weekly", "groceries"],
        "created_at": (datetime.utcnow() - timedelta(days=90)).isoformat(),
        "updated_at": (datetime.utcnow() - timedelta(days=14)).isoformat(),
        "last_activity": "Archived by admin@example.com 14d ago",
    },
]

activity_store = [
    {"id": i+1, "project_id": random.choice([1, 2]),
     "user": random.choice(["admin@example.com", "analyst@example.com", "manager@example.com"]),
     "action": random.choice(["Ran forecast", "Uploaded dataset", "Added comment", "Generated report", "Invited member", "Updated settings"]),
     "detail": random.choice(["Random Forest - Electronics", "sales_nov.csv", "Check accuracy for Q4", "Monthly PDF", "analyst@example.com", "Changed region to All"]),
     "timestamp": (datetime.utcnow() - timedelta(hours=i*3)).isoformat()}
    for i in range(25)
]

def _next_id():
    return max((p["id"] for p in projects_store), default=0) + 1

@router.get("/", summary="List all projects")
def list_projects(status: Optional[str] = Query(None), owner: Optional[str] = Query(None), search: Optional[str] = Query(None)):
    data = list(projects_store)
    if status:
        data = [p for p in data if p["status"] == status]
    if owner:
        data = [p for p in data if p["owner"] == owner]
    if search:
        s = search.lower()
        data = [p for p in data if s in p["name"].lower() or s in p["description"].lower()]
    return {"projects": data, "total": len(data),
            "active": sum(1 for p in data if p["status"] == "active"),
            "archived": sum(1 for p in data if p["status"] == "archived")}

@router.get("/summary", summary="Workspace stats summary")
def workspace_summary():
    return {
        "total_projects": len(projects_store),
        "active_projects": sum(1 for p in projects_store if p["status"] == "active"),
        "total_forecasts": sum(p["forecast_count"] for p in projects_store),
        "total_datasets": sum(p["dataset_count"] for p in projects_store),
        "total_reports": sum(p["report_count"] for p in projects_store),
        "total_members": len(set(m for p in projects_store for m in p["members"])),
    }

@router.get("/{project_id}", summary="Get project details")
def get_project(project_id: int):
    for p in projects_store:
        if p["id"] == project_id:
            return p
    raise HTTPException(404, "Project not found")

@router.post("/", status_code=201, summary="Create project")
def create_project(payload: dict):
    if not payload.get("name"):
        raise HTTPException(422, "name is required")
    now = datetime.utcnow().isoformat()
    proj = {
        "id": _next_id(), "name": payload["name"],
        "description": payload.get("description", ""),
        "owner": payload.get("owner", "admin@example.com"),
        "members": payload.get("members", [payload.get("owner", "admin@example.com")]),
        "status": "active", "category": payload.get("category", "All"),
        "region": payload.get("region", "All"),
        "dataset_count": 0, "forecast_count": 0, "report_count": 0,
        "permissions": {"view": ["all"], "edit": ["admin"], "delete": ["admin"]},
        "tags": payload.get("tags", []),
        "created_at": now, "updated_at": now,
        "last_activity": f"Project created by {payload.get('owner','admin@example.com')}",
    }
    projects_store.append(proj)
    return proj

@router.put("/{project_id}", summary="Update project")
def update_project(project_id: int, payload: dict):
    for p in projects_store:
        if p["id"] == project_id:
            for k in ["name", "description", "status", "category", "region", "tags", "members", "permissions"]:
                if k in payload:
                    p[k] = payload[k]
            p["updated_at"] = datetime.utcnow().isoformat()
            return p
    raise HTTPException(404, "Project not found")

@router.delete("/{project_id}", summary="Delete project")
def delete_project(project_id: int):
    global projects_store
    proj = next((p for p in projects_store if p["id"] == project_id), None)
    if not proj:
        raise HTTPException(404, "Project not found")
    projects_store = [p for p in projects_store if p["id"] != project_id]
    return {"message": f"Project '{proj['name']}' deleted"}

@router.put("/{project_id}/archive", summary="Archive/unarchive project")
def toggle_archive(project_id: int):
    for p in projects_store:
        if p["id"] == project_id:
            p["status"] = "archived" if p["status"] == "active" else "active"
            p["updated_at"] = datetime.utcnow().isoformat()
            return p
    raise HTTPException(404, "Project not found")

@router.get("/{project_id}/activity", summary="Project activity log")
def get_activity(project_id: int, limit: int = Query(20)):
    data = [a for a in activity_store if a["project_id"] == project_id]
    return {"activity": list(reversed(data))[:limit], "total": len(data)}

@router.post("/{project_id}/members", summary="Add member to project")
def add_member(project_id: int, payload: dict):
    email = payload.get("email")
    if not email:
        raise HTTPException(422, "email is required")
    for p in projects_store:
        if p["id"] == project_id:
            if email not in p["members"]:
                p["members"].append(email)
                p["updated_at"] = datetime.utcnow().isoformat()
            return {"message": f"{email} added to project", "members": p["members"]}
    raise HTTPException(404, "Project not found")

@router.delete("/{project_id}/members/{email}", summary="Remove member")
def remove_member(project_id: int, email: str):
    for p in projects_store:
        if p["id"] == project_id:
            p["members"] = [m for m in p["members"] if m != email]
            p["updated_at"] = datetime.utcnow().isoformat()
            return {"message": f"{email} removed", "members": p["members"]}
    raise HTTPException(404, "Project not found")
